### ISSUE TITLE
적으로 할 이미지 찾아서 images 폴더에 올려주세요

### ISSUE THREAD

**Issue by JeesooHa** [JeesooHa/8team#11]
적으로 넣을 이미지가 필요해서 그런데 괜찮은 이미지 올려주세요

갯수는 상관없고 여러개 올려주시면 적당한거 고르도록 할께요

이왕이면 배경까지 나온거 말고 본체(수정한 비행기 이미지처럼)만 있는거면 좋겠습니다.

정해진 분만 올리는게 아니라 다 올리셔도 됩니다.

**Comment by JeesooHa** [comment]
적 이미지 대충 UFO로 넣기는 했는데 좀 이상한거 같네요 좋은 사진 뭐 없을까요?

**Comment by zoowx321** [comment]
적 사진 올렸습니다. 배경 수정은 어떻게 하는 걸까요? :)

**Comment by WooJin-JO** [comment]
배경 수정은 생각보다 간단하니까 적 이미지 결정되면 제가 수정하는걸로 하죠

**Comment by JeesooHa** [comment]
우선 background1 이랑 enemy2, enemy_explosion, enemy_shot 사용하고 나머지는 추후에 더 추가하던가 하겠습니다.

**Comment by JeesooHa** [comment]
올린 이미지들로 코드 작성 했습니다. 확인 한번 해주시고 이상한점 말씀해주세요^^

**Comment by KimDaehan** [comment]
적 사진까지 적용 끝났으면 이거 닫아도될거같습니당.. 죄송해요 주말에 일이 좀 있어서 이제부터 열심히 참여하겠습니당.
