### ISSUE TITLE
게임 사운드 추가

### ISSUE THREAD

**Issue by JeesooHa** [JeesooHa/8team#13]
[슈팅게임 - 아홉번째](http://blog.naver.com/dosem321/40171931241)

위의 내용처럼 게임에 사운드를 추가하려고 합니다.

게임 중 계속 재생될 배경음과 격추시 재생할 폭발음 파일을 찾아주세요.

**Comment by WooJin-JO** [comment]
bgm을 wav로 변환해서 올려놨는데 원본에 비해서 용량이 많이 커졋네요
mp3형식으로 해도 상관 없나요?
어제 깜빡해서 연속 contributions가 깨졌다 ㅠㅠ

**Comment by JeesooHa** [comment]
우선 우진씨가 올려주신 것들을 반영하였고요 미사일 발사음이나 게임시작 종료음 등 다양한거 올려주시면
감사하겠습니다.

자세한건 내일 수업시간에 모였을때 간단히 이야기 해봐요

**Comment by WooJin-JO** [comment]
enemy_charge_shots => #23 에서 boss_laser_guide이미지 사용 될 때 사용할 사운드 입니다.
enemy_warning before_the_charge_shot => #23 에서 boss_laser_guide 전 미리 알려줌에서 경고음 입니다
enemy_normal_shot => #23 보스 노말 공격 사운드입니다.
user_shots => 플레이어 기본 공격 사운드 입니다.

**Comment by WooJin-JO** [comment]
enemy_charge_shots이 지금 4초인데 시간 수정해야하면 말해주세요
