### ISSUE TITLE
스테이지 로고

### ISSUE THREAD

**Issue by zoowx321** [JeesooHa/8team#25]
- [x] 1. 스테이지 로고 이미지 파일 올리기

- [x] 2. 코드에 삽입하기

**Comment by JeesooHa** [comment]
스테이지 로고 이미지를 잘라서 글자로 만들어줘야 적용하기 편리합니다. 수정 부탁드려요

**Comment by KimDaehan** [comment]
정확히 어떤걸 잘라달라는 말인지 모르겠어요~설명좀ㅎ ㅐ주세요.

**Comment by JeesooHa** [comment]
스테이지 로고 이미지 보면 0 1 2 3 4 ... 이런식으로 숫자와 문자 나열로 되어 있는데 이게 stage clear와 같이 한 문장이 하나의 이미지에 있어야 사용 가능합니다.

**Comment by WooJin-JO** [comment]
이렇게 말하신거 맞죠?
일단 stage 03까지 만들었습니다. 더 필요할까요?

**Comment by JeesooHa** [comment]
네 맞습니다.  GAME START도 만드실 수 있나요?

**Comment by WooJin-JO** [comment]
어.... M이 없는데요?

**Comment by JeesooHa** [comment]
이런. . .  그럼. Start만 부탁드려요

**Comment by zoowx321** [comment]
- [x]  스테이지 클리어 삽입하기
