### ISSUE TITLE
발표 관련 추가사항 있으면 말씀해주세요.

### ISSUE THREAD

**Issue by KimDaehan** [JeesooHa/8team#32]
발표 관련 추가사항 있으면 말씀해주세요.

피티 제작 이후에 추가사항 있거나, 논의된거 외적으로 다른 발표에 꼭 추가되어야 하는 사항 있으면 발씀해주세요.

**Comment by WooJin-JO** [comment]
ppt에 페이지 번호가 달려있는 곳이 있고 없는 곳이 있어요

**Comment by zoowx321** [comment]
why? 부분에 오타가 있네요.
make an game -> make a game

**Comment by zoowx321** [comment]
Present State 부분에 설명하는 부분들 글자 크기가 너무 작은것 같습니다.

**Comment by WooJin-JO** [comment]
Our Wiki 바로 뒤에 Member's role가 나오는데 Our Wiki  마지막에 나오는 팀원 & Role 자르고 윗부분을 좀 크게 하는건 어떤가요
그리고 저도 How to play, Present State, What to do later 글자 크기 늘리면 좋을것 같습니다.
마지막으로 Index 페이지 오른쪽은 글자가 빽빽한것에 비해서 왼쪽이 여백이 너무 남는데 2개 열로 나누고 앞에 글머리 기호를 숫자로 바꾸는건 어떤가요?

**Comment by KimDaehan** [comment]
네  일단 여기까지 반영했습니다.
