### ISSUE TITLE
Readme.me 에서 팀원&role 부분 수정

### ISSUE THREAD

**Issue by zoowx321** [JeesooHa/8team#33]
PPt에서 member 슬라이드에 있는게 더 깔끔하고 정리도 잘되있는 것 같은데 이걸로 교체하는게 어떨까요?

**Comment by KimDaehan** [comment]
네 저는 동의합니다 나머지 분들 동의하시면 코멘트 달아주시고 마지막분이 수정해주세요,

**Comment by WooJin-JO** [comment]
저도 동의합니다

**Comment by JeesooHa** [comment]
저도 동의합니다.

**Comment by JeesooHa** [comment]
수정했습니다
