### ISSUE TITLE
보스 몬스터와 궁극기 확인

### ISSUE THREAD

**Issue by JeesooHa** [JeesooHa/8team#36]
보스 몬스터, 궁극기, game over 구현하였습니다.

보스 몬스터는 유저의 점수가 200 점일때 등장하게 했고 10번 미사일 맞으면 죽습니다. 아직 확인을 위해 등장하는 타이밍을 빠르게 했고 추후에 수정 가능합니다.

궁극기는 게임 점수를 150점 얻을 때마다 하나씩 얻고 효과는 미사일과 보스를 제외한 적들이 사라지는 것 입니다.

game over의 경우는 유저의 hp가 0이 되면 소리와 함게 게임 오버라는 그림이 뜨게 되어 있으며 아직 다시 시작할 수 있는 기능은 추가하지 않았습니다.

start.jar 파일을 돌려보시고 확인 및 수정할 상황을 올려주세요.

**Comment by WooJin-JO** [comment]
보스를 죽이고 나서 진행이 안되고요 그리고 궁극기를 사용했을때  적들이 일부만 사라집니다.
나머지는 알맞게 구현되는것 같습니다.

**Comment by JeesooHa** [comment]
아직 다시 시작은 구현 안했고 궁극기는 타이밍 문제 같은데 수정하도록 하겠습니다.

**Comment by zoowx321** [comment]
보스가 출현하는 조건을 변경했습니다.
-200점 획득할때 마다 보스 출현.

**Comment by WooJin-JO** [comment]
보스의 공격이 너무 보스 이미지 상단에서 나갑니다. 보스 이미지 기준으로 중간에 있으면 보스 공격을 맞지않고 너무 쉽게 잡을 수 있습니다. 그리고 총알의 속도가 빨라서 보스의 hp를 더 늘려도 될 것 같습니다.

**Comment by JeesooHa** [comment]
적용 했습니다. 다시 확인 부탁드리고 문제점은 이슈로 만들어 주세요.
