### ISSUE TITLE
개선해야할 것들 #2

### ISSUE THREAD

**Issue by zoowx321** [JeesooHa/8team#38]
- [x] 스테이지 시작시 현재 스테이지 숫자가 뜬 후 시작하게 하기
- [x] 보스 출현할 때 기존의 적들이 다 없어진 후 나타나게 하고 보스가 출현하면 더이상 안나타나게 하기
(보스가 나오는 조건이 200점 획득시마다로 바뀌었기 때문에 중복 출현을 막기 위해서)

**Comment by JeesooHa** [comment]
수정 완료 게임 돌려서 확인해보세요.

**Comment by zoowx321** [comment]
보스 출현시 더이상 기존 적들이 안나타나게 변경하였습니다.

**Comment by WooJin-JO** [comment]
어제 패치로 보스체력이 늘어났는데 이로인해서 생기는 필살기가 너무 많아졌습니다.
필살기 획득 점수를 늘리던지 보스로 인해 얻는 점수를 낮추는 방법이 필요할것 같습니다.

**Comment by JeesooHa** [comment]
궁극기를 얻는 점수를 150에서 200으로 올렸습니다..
