### ISSUE TITLE
게임 초기 스토리 만들기 및 스타워즈 배경음 추가

### ISSUE THREAD

**Issue by JeesooHa** [JeesooHa/8team#42]
- [x] 게임 시작 이전 들어갈 설명

- [x] 스타워즈 배경음악

**Comment by KimDaehan** [comment]
게임 시작전 배경은 제가 해서 올리겠습니다.

**Comment by zoowx321** [comment]
배경음악 업로드 했습니다. 소스에 추가할께요.

**Comment by WooJin-JO** [comment]
스토리 만들어지면 제가 스타워즈처럼 만들어 보겠습니다.
검색해보니까 의외로 간단하네요 만들때 쓰는 프로그램도 무료 체험판도 있고
