### ISSUE TITLE
보스 패턴 변화

### ISSUE THREAD

**Issue by zoowx321** [JeesooHa/8team#43]
현재 보스의 공격패턴이 너무 단조롭습니다.

보스를 움직이게 하거나 보스의 공격이 단순히 일직선이 아니라 유저에게 향하도록 바꾸는건 어떨까요?

**Comment by WooJin-JO** [comment]
어제 위쪽으로 총알이 나오던게 수정되서 가운데로 나오지만 여전히 맞지않고 공격할수가 있습니다. 공격을 위, 아래, 중간으로 동시에 나가게 하거나 위, 아래, 중간 세곳 중 1곳에서 랜덤하게 공격하는것도 좋을것같습니다. 그리고 총알의 발사 텀을 좀 더 빠르게 하고요

**Comment by zoowx321** [comment]
@WooJin-JO 반영하도록 하겠습니다.

**Comment by zoowx321** [comment]
@WooJin-JO 수정했습니다. 확인해보시고 추가로 수정할 것이 있으면 알려주세요

**Comment by WooJin-JO** [comment]
pull해서 해봤는데 보스가 그대로인데요.....

**Comment by zoowx321** [comment]
@WooJin-JO 어떻게 실행하셨나요? src폴더에 있는 game으로 하면 잘 나오는데.........
