### ISSUE TITLE
수정이 필요한 부분

### ISSUE THREAD

**Issue by WooJin-JO** [JeesooHa/8team#45]
- [x] 보스와 부딪치면 보스가 죽습니다.... 플레이어는 hp1만 감소하고요
(보스가 죽지 않게하던지 아니면 플레이어 hp를 한번에 3을 감소시켜서 죽게하는게 좋을 것 같습니다.)
그리고 이렇게 보스를 죽이게되면 스테이지가 넘어가지 않습니다.

- [x] 저희의 목표가 스테이지 3까지라면 크게 수정할 필요없는 부분이긴 한데
스테이지 6정도되면 보스 공격이 거의 발사와 동시에 도착합니다....
스테이지마다 미사일 속도가 +4이던데 +2 정도가 적당할듯 합니다.
(이건 스테이지 4이상을 구현할때의 문제이고 스테이지 3까지가 목표라면 적당한 난이도라고 생각합니다.)

**Comment by zoowx321** [comment]
미사일 속도 2로 수정했습니다.

**Comment by JeesooHa** [comment]
첫번째 문제는 보스와 부딪치면 죽는 것으로 했습니다. hp만 깎으려면 대대적으로 수정해야해서 죽는걸로 했습니다

**Comment by JeesooHa** [comment]
stage3까지만 생각하고 있는터라 추후에 게임 난이도를 보고 수정하면 될꺼 같습니다
