### ISSUE TITLE
보스 추가로 인한 필요한 수정 사항

### ISSUE THREAD

**Issue by WooJin-JO** [JeesooHa/8team#46]
- [x] 2스테이지와 3스테이지 보스에게 궁극기 스킬 사용시 보스가 죽습니다.

- [x] 위의 경우 스테이지가 넘어가지 않습니다.

- [x] 지금 현재의 교수님 이미지의 보스를 2 또는 3스테이지로하고 현재 2스테이지 보스를 1스테이지 보스 3스테이지 보스를 2 또는 3스테이지 보스로 하는건 어떨런지요

현재까지 확인한것은 위에 것들입니다.

**Comment by zoowx321** [comment]
1,2,번 버그 수정하였습니다. @WooJin-JO

**Comment by JeesooHa** [comment]
보스 순서 바꿨습니다. 확인해보시고 ufo 사진 배경 흰색도 없애주세요.
