### ISSUE TITLE
스타워즈 오프닝

### ISSUE THREAD

**Issue by WooJin-JO** [JeesooHa/8team#50]
- [x] 스타워즈 오프닝 만들어서 올리기

**Comment by WooJin-JO** [comment]
한번 보시고 수정필요한부분 말해주세요
수정이 가능한 영역일지는 모르겠지만요.....
그리고 무료 체험용 프로그램이 1주일이라서 9일 전에 말해주셔야 수정 가능합니다.

**Comment by JeesooHa** [comment]
글자가 잘 안보여서 그러는데 글자 사라지는걸 조금 더 위로 하고 속도 천천히 가능한가요?

**Comment by JeesooHa** [comment]
괜찮은거 같습니다. 수고하셨어요.
