### ISSUE TITLE
코딩시작.

### ISSUE THREAD

**Issue by KimDaehan** [JeesooHa/8team#6]
기존 가진 소스와 합작해서 프로젝트 본격적으로  시작해야할듯 합니당.

**Comment by WooJin-JO** [comment]
넵 시작해 봅시다

**Comment by WooJin-JO** [comment]
네 잘해봐요
이걸로도 contributions가 올라가려나....

**Comment by jssngg** [comment]
넵

**Comment by jssngg** [comment]
예

**Comment by jssngg** [comment]
헉 댓글 창닫기라고 생각하고 close and comment 눌렀다가 다시 열었습니다. 이슈는 안전합니다,

**Comment by WooJin-JO** [comment]
안타까운 소식입니다만 이 댓글로는 contributions가 안올라가는것 같습니다.
