### ISSUE TITLE
이미지 수정

### ISSUE THREAD

**Issue by JeesooHa** [JeesooHa/8team#8]
- [ ] images 폴더 안에 있는 plane_img 파일 수정
비행기의 흰 배경이 안보이게 누가 수정해주세요

**Comment by WooJin-JO** [comment]
누가 제대로 됬는지 확인하고 이슈 닫아주세요

**Comment by WooJin-JO** [comment]
아 혹시 몰라서 branch도 해놨으니 merge도 해주세요

**Comment by KimDaehan** [comment]
일단은 잘 된거같아서 이슈 닫습니다.
